import type { PlayerTableState } from "./types";

export function createDemoTableState(): PlayerTableState {
  return {
    tournament_id: "demo",
    tournament_status: "running",
    table_status: "running",
    table_id: "table-03",
    hand_id: "table-03-hand-18",
    hand_number: 18,
    table_version: 47,
    viewer_seat: 4,
    acting_seat: 4,
    street: "flop",
    button_seat: 2,
    small_blind: 100,
    big_blind: 200,
    big_blind_ante: 200,
    community_cards: ["Qh", "7c", "2d"],
    seats: [
      {
        seat: 1,
        entrant_id: "river-runner",
        display_name: "RiverRunner",
        kind: "bot",
        stack: 23600,
        committed_this_street: 600,
        committed_this_hand: 1000,
        folded: false,
        all_in: false,
        eliminated: false,
        hole_cards: [],
      },
      {
        seat: 2,
        entrant_id: "maya",
        display_name: "Maya",
        kind: "human",
        stack: 17100,
        committed_this_street: 600,
        committed_this_hand: 1000,
        folded: false,
        all_in: false,
        eliminated: false,
        hole_cards: [],
      },
      {
        seat: 3,
        entrant_id: "tight-loop",
        display_name: "tight_loop.py",
        kind: "bot",
        stack: 14200,
        committed_this_street: 0,
        committed_this_hand: 200,
        folded: true,
        all_in: false,
        eliminated: false,
        hole_cards: [],
      },
      {
        seat: 4,
        entrant_id: "viewer",
        display_name: "You",
        kind: "human",
        stack: 18400,
        committed_this_street: 0,
        committed_this_hand: 400,
        folded: false,
        all_in: false,
        eliminated: false,
        hole_cards: ["As", "Kh"],
      },
      {
        seat: 5,
        entrant_id: "call-station",
        display_name: "CallStation",
        kind: "bot",
        stack: 9800,
        committed_this_street: 0,
        committed_this_hand: 300,
        folded: true,
        all_in: false,
        eliminated: false,
        hole_cards: [],
      },
      {
        seat: 6,
        entrant_id: "devon",
        display_name: "Devon",
        kind: "human",
        stack: 20700,
        committed_this_street: 0,
        committed_this_hand: 200,
        folded: true,
        all_in: false,
        eliminated: false,
        hole_cards: [],
      },
    ],
    pot: 2200,
    side_pots: [],
    action_history: [
      {
        sequence: 8,
        seat: 3,
        action: "check",
        amount_to: null,
        automatic: false,
        failure_reason: null,
      },
      {
        sequence: 9,
        seat: 4,
        action: "check",
        amount_to: null,
        automatic: false,
        failure_reason: null,
      },
      {
        sequence: 10,
        seat: 1,
        action: "raise",
        amount_to: 600,
        automatic: false,
        failure_reason: null,
      },
      {
        sequence: 11,
        seat: 2,
        action: "call",
        amount_to: null,
        automatic: false,
        failure_reason: null,
      },
      {
        sequence: 12,
        seat: 3,
        action: "fold",
        amount_to: null,
        automatic: true,
        failure_reason: "timeout",
      },
    ],
    completed: false,
    decision: {
      decision_id: "demo-decision-48",
      table_version: 47,
      deadline_at: new Date(Date.now() + 30_000).toISOString(),
      legal_actions: [
        { action: "fold", amount: null, min_amount_to: null, max_amount_to: null },
        { action: "call", amount: 600, min_amount_to: null, max_amount_to: null },
        { action: "raise", amount: null, min_amount_to: 1800, max_amount_to: 18400 },
      ],
    },
  };
}
